Completed prep-html-links exercise - Nelson David Daza
neldaza/prep-0721-code-solutions pull request #4
Opened 2021-07-31 21:35 UTC by neldaza

<img width="790" alt="Screen Shot 2021-07-31 at 5 29 50 PM" src="https://user-images.githubusercontent.com/88061673/127752919-a2fd53a3-9eec-4bdc-951d-b180d254ec6f.png">
<img width="759" alt="Screen Shot 2021-07-31 at 5 28 07 PM" src="https://user-images.githubusercontent.com/88061673/127752929-ed366522-ea59-48e3-b49a-8fc1b27da9c5.png">

2021-08-01 18:24 UTC, thebearingedge requested changes
Hi Nelson, your directory structure looks different from the starter files. The `index.html` and `contact-us.html` files shouldn't be located in the same directory.

```plain
prep-html-links/
├── contact-us/
│   └── contact-us.html
├── .gitkeep
├── .npmrc
└── index.html

```

2021-08-02 20:25 UTC, neldaza reviewed
Noted! edited and finished as such, both hyperlinks now active with original directory placement

2021-08-02 22:06 UTC, thebearingedge requested changes

2021-08-02 22:06 UTC, thebearingedge commented on prep-html-links/contact-us/contact-us.html
> +  <a href= "prep-html-links/index.html">Click here to go to the home page</a>
We are getting much closer 👍 . Here we want to use a relative path `href="../index.html"` so that these files don't need to necessarily be inside of a `prep-html-links` directory to still link properly.

2021-08-02 22:06 UTC, thebearingedge commented on prep-html-links/index.html
> +  <a href= "prep-html-links/contact-us/contact-us.html">Click here to go to the contact page</a>
We are getting much closer 👍 . Here we want to use a relative path `href="contact-us/contact-us.html"` so that these files don't need to necessarily be inside of a `prep-html-links` directory to still link properly.

2021-08-03 00:15 UTC, neldaza commented
Noted and updated through commit! Thanks Tim! 


<img width="838" alt="Screen Shot 2021-08-02 at 8 13 20 PM" src="https://user-images.githubusercontent.com/88061673/127938662-1af9f5a1-0575-4e03-9a80-a09b2193ceaa.png">
<img width="811" alt="Screen Shot 2021-08-02 at 8 12 34 PM" src="https://user-images.githubusercontent.com/88061673/127938666-adf7401a-1072-4e9e-aa74-35bda3779ff5.png">

2021-08-03 19:00 UTC, thebearingedge requested changes

2021-08-03 19:00 UTC, thebearingedge commented on prep-html-links/contact-us/contact-us.html
> +  <a href= "index.html">Click here to go to the home page</a>
This might be an outdated commit, but you want your `href` to be `"../index.html"` so that the browser knows to load the `index.html` in the parent directory.

2021-08-04 22:13 UTC, thebearingedge requested changes

2021-08-04 22:13 UTC, thebearingedge commented on prep-html-links/index.html
> +  <a href= "../contact-us.html">Click here to go to the contact page</a>
Hi Nelson, this `..` here wasn't needed, we just needed the `../index.html` in the other file. This one should still be `"contact-us/contact-us.html"`.

2021-08-06 00:04 UTC, neldaza commented on prep-html-links/index.html
> +  <a href= "../contact-us.html">Click here to go to the contact page</a>
aye aye captain! Hopefully this rendition finishes the job properly, thanks for your patience Tim

N


<img width="862" alt="Screen Shot 2021-08-05 at 8 02 18 PM" src="https://user-images.githubusercontent.com/88061673/128436414-dd7dd5d7-1817-4213-bdf6-2f61838d4d93.png">
<img width="803" alt="Screen Shot 2021-08-05 at 8 01 36 PM" src="https://user-images.githubusercontent.com/88061673/128436416-c0fe4894-2c0c-4848-bb74-541c42f5f025.png">

2021-08-06 03:47 UTC, thebearingedge approved these changes
All set!

2021-08-07 15:29 UTC, merged